config/routes.rb
Rails.application.routes.draw do

  resources :people do

  end

  resources :countries, only: [:index, :new, :create] do

  end

end

app/models/Person.rb
class Person < ActiveRecord::Base

end

app/models/country.rb
class Country < ActiveRecord::Base

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController

  def index
    @countries = Country.all
  end

  def new
    @countries = Country.all
    @country = Country.new
  end

  def create
    @country = Country.new(country_params)
    respond_to do |format|
      if @country.save
        format.html { redirect_to new_country_path, notice: 'Country was successfully created.' }
        format.js
        format.json { render json: @country, status: :created, location: @country }
      else
        format.html { render action: "new" }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end


  protected

  def country_params
    params.require(:country).permit(:name)
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController

  def index
    @people = Person.all
  end

  def new
    @people = Person.all
    @person = Person.new
  end

  def create
    @person = Person.new(person_params)
    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.js
        format.json { render json: @person, status: :created, location: @person }
      else
        format.html { render action: "new" }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @person = Person.find(params[:id])
    @person.destroy

    respond_to do |format|
      format.html { redirect_to new_person_path }
      format.json { head :no_content }
      format.js   { render :layout => false }
    end
  end

  protected

  def person_params
    params.require(:person).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/People/_person.html.erb
<li id="name-<%=person.id%>">
  <%= person.name %>
  <%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' }, :remote => true, :class =>
      'delete_person' %>
</li>

app/views/People/create.js.erb
$("<%= escape_javascript(render @person) %>").appendTo("#people");

app/views/People/index.html.erb
<ul>
  <% @people.each do |person| %>
    <li id="name-<%=person.id%>">
      <%= person.name %>
      <%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' }, :remote => true, :class =>
    'delete_person' %>
    </li>
  <% end %>
</ul>

app/views/People/new.html.erb
<%= form_for @person, remote: true do |f| %>
  <%= f.label :name %>:
  <%= f.text_field :name %>

  <%= f.submit %>
<% end %>

<ul id="people">
  <%render @people %>
</ul>

app/views/countries/_country.html.erb
<li><%= country.name %></li>

app/views/countries/create.js.erb
$("<%= escape_javascript(render @country) %>").appendTo("#countries");

app/views/countries/index.html.erb
<ul>
  <% @countries.each do |country| %>
    <li><%= country.name %></li>
  <% end %>
</ul>

<%= link_to "Add countries", new_country_path %>

app/views/countries/new.html.erb
<%= form_for @country, remote: true do |f| %>
  <%= f.label :name %>:
  <%= f.text_field :name %>

  <%= f.submit %>
<% end %>


<ul id="countries">
  <%render @countries %>
</ul>

<%= link_to "View all countries", countries_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ventipercento</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/people/destroy.js.erb
$('.delete_person').bind('ajax:success', function() {
  $("#name-<%= @person.id %>").remove();
});